# This playbook Illustartes, How to add multiple values at the end of the file
# Using lineinfile module However, insertafter says "inject the line End of the File
# And we will set the line to be inserted using the line parameter.
---
- name: Playbook to add a multiline values to sysctl.conf file
  hosts: all
  remote_user: root
  gather_facts: False
  tasks:
    - name: taking the backup of the file /etc/sysctl.conf
      shell: cp /etc/sysctl.conf /etc/sysctl.conf-org

    - name: add the new kernel parameters at the end of sysctl.conf file
      lineinfile: dest=/etc/sysctl.conf
                  insertafter=EOF
                  line='vm.overcommit_ratio = 100\nvm.overcommit_memory = 2'

    - name: make changes to sysctl.conf file permanently
      shell: sysctl -p



======================================
# Result after using above Playbook
======================================
$ cat /etc/sysctl.conf
# System default settings live in /usr/lib/sysctl.d/00-system.conf.
# To override those settings, enter new settings here, or in an /etc/sysctl.d/<name>.conf file
#
# For more information, see sysctl.conf(5) and sysctl.d(5).
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
vm.overcommit_ratio = 100             <-- This line was added by above play
vm.overcommit_memory = 2              <-- This line was added by above play

